project:
  render: 
    - "**/*.qmd"
    - "**/*.ipynb"

format:
  commonmark:
    variant: +tex_math_dollars
    keep-yaml: true
    wrap: none
    filters: 
      - docusaurus.lua
      - quarto
    
